// This file is auto-generated by generate_mappings.py. DO NOT EDIT DIRECTLY.
use crate::card::*;

pub fn parse_supertype(s: &str) -> Option<Supertype> {
    match s.to_lowercase().as_str() {
        "basic" => Some(Supertype::Basic),
        "legendary" => Some(Supertype::Legendary),
        "ongoing" => Some(Supertype::Ongoing),
        "snow" => Some(Supertype::Snow),
        "world" => Some(Supertype::World),
        _ => None,
    }
}

pub fn parse_cardtype(s: &str) -> Option<CardType> {
    match s.to_lowercase().as_str() {
        "artifact" => Some(CardType::Artifact),
        "battle" => Some(CardType::Battle),
        "conspiracy" => Some(CardType::Conspiracy),
        "creature" => Some(CardType::Creature),
        "dungeon" => Some(CardType::Dungeon),
        "enchantment" => Some(CardType::Enchantment),
        "instant" => Some(CardType::Instant),
        "kindred" => Some(CardType::Kindred),
        "land" => Some(CardType::Land),
        "phenomenon" => Some(CardType::Phenomenon),
        "plane" => Some(CardType::Plane),
        "planeswalker" => Some(CardType::Planeswalker),
        "scheme" => Some(CardType::Scheme),
        "sorcery" => Some(CardType::Sorcery),
        "vanguard" => Some(CardType::Vanguard),
        _ => None,
    }
}

pub fn parse_artifacttype(s: &str) -> Option<ArtifactType> {
    match s.to_lowercase().as_str() {
        "attraction" => Some(ArtifactType::Attraction),
        "blood" => Some(ArtifactType::Blood),
        "bobblehead" => Some(ArtifactType::Bobblehead),
        "book" => Some(ArtifactType::Book),
        "clue" => Some(ArtifactType::Clue),
        "contraption" => Some(ArtifactType::Contraption),
        "equipment" => Some(ArtifactType::Equipment),
        "food" => Some(ArtifactType::Food),
        "fortification" => Some(ArtifactType::Fortification),
        "gold" => Some(ArtifactType::Gold),
        "incubator" => Some(ArtifactType::Incubator),
        "infinity" => Some(ArtifactType::Infinity),
        "junk" => Some(ArtifactType::Junk),
        "lander" => Some(ArtifactType::Lander),
        "map" => Some(ArtifactType::Map),
        "mutagen" => Some(ArtifactType::Mutagen),
        "powerstone" => Some(ArtifactType::Powerstone),
        "spacecraft" => Some(ArtifactType::Spacecraft),
        "stone" => Some(ArtifactType::Stone),
        "treasure" => Some(ArtifactType::Treasure),
        "vehicle" => Some(ArtifactType::Vehicle),
        _ => None,
    }
}

pub fn parse_enchantmenttype(s: &str) -> Option<EnchantmentType> {
    match s.to_lowercase().as_str() {
        "aura" => Some(EnchantmentType::Aura),
        "background" => Some(EnchantmentType::Background),
        "cartouche" => Some(EnchantmentType::Cartouche),
        "case" => Some(EnchantmentType::Case),
        "class" => Some(EnchantmentType::Class),
        "curse" => Some(EnchantmentType::Curse),
        "role" => Some(EnchantmentType::Role),
        "room" => Some(EnchantmentType::Room),
        "rune" => Some(EnchantmentType::Rune),
        "saga" => Some(EnchantmentType::Saga),
        "shard" => Some(EnchantmentType::Shard),
        "shrine" => Some(EnchantmentType::Shrine),
        _ => None,
    }
}

pub fn parse_landtype(s: &str) -> Option<LandType> {
    match s.to_lowercase().as_str() {
        "cave" => Some(LandType::Cave),
        "desert" => Some(LandType::Desert),
        "forest" => Some(LandType::Forest),
        "gate" => Some(LandType::Gate),
        "island" => Some(LandType::Island),
        "lair" => Some(LandType::Lair),
        "locus" => Some(LandType::Locus),
        "mine" => Some(LandType::Mine),
        "mountain" => Some(LandType::Mountain),
        "plains" => Some(LandType::Plains),
        "planet" => Some(LandType::Planet),
        "power-plant" => Some(LandType::PowerPlant),
        "sphere" => Some(LandType::Sphere),
        "swamp" => Some(LandType::Swamp),
        "tower" => Some(LandType::Tower),
        "town" => Some(LandType::Town),
        "urza's" => Some(LandType::Urzas),
        _ => None,
    }
}

pub fn parse_planeswalkertype(s: &str) -> Option<PlaneswalkerType> {
    match s.to_lowercase().as_str() {
        "ajani" => Some(PlaneswalkerType::Ajani),
        "aminatou" => Some(PlaneswalkerType::Aminatou),
        "angrath" => Some(PlaneswalkerType::Angrath),
        "arlinn" => Some(PlaneswalkerType::Arlinn),
        "ashiok" => Some(PlaneswalkerType::Ashiok),
        "bahamut" => Some(PlaneswalkerType::Bahamut),
        "basri" => Some(PlaneswalkerType::Basri),
        "bolas" => Some(PlaneswalkerType::Bolas),
        "calix" => Some(PlaneswalkerType::Calix),
        "chandra" => Some(PlaneswalkerType::Chandra),
        "comet" => Some(PlaneswalkerType::Comet),
        "dack" => Some(PlaneswalkerType::Dack),
        "dakkon" => Some(PlaneswalkerType::Dakkon),
        "daretti" => Some(PlaneswalkerType::Daretti),
        "davriel" => Some(PlaneswalkerType::Davriel),
        "dellian" => Some(PlaneswalkerType::Dellian),
        "dihada" => Some(PlaneswalkerType::Dihada),
        "domri" => Some(PlaneswalkerType::Domri),
        "dovin" => Some(PlaneswalkerType::Dovin),
        "ellywick" => Some(PlaneswalkerType::Ellywick),
        "elminster" => Some(PlaneswalkerType::Elminster),
        "elspeth" => Some(PlaneswalkerType::Elspeth),
        "estrid" => Some(PlaneswalkerType::Estrid),
        "freyalise" => Some(PlaneswalkerType::Freyalise),
        "garruk" => Some(PlaneswalkerType::Garruk),
        "gideon" => Some(PlaneswalkerType::Gideon),
        "grist" => Some(PlaneswalkerType::Grist),
        "guff" => Some(PlaneswalkerType::Guff),
        "huatli" => Some(PlaneswalkerType::Huatli),
        "jace" => Some(PlaneswalkerType::Jace),
        "jared" => Some(PlaneswalkerType::Jared),
        "jaya" => Some(PlaneswalkerType::Jaya),
        "jeska" => Some(PlaneswalkerType::Jeska),
        "kaito" => Some(PlaneswalkerType::Kaito),
        "karn" => Some(PlaneswalkerType::Karn),
        "kasmina" => Some(PlaneswalkerType::Kasmina),
        "kaya" => Some(PlaneswalkerType::Kaya),
        "kiora" => Some(PlaneswalkerType::Kiora),
        "koth" => Some(PlaneswalkerType::Koth),
        "liliana" => Some(PlaneswalkerType::Liliana),
        "lolth" => Some(PlaneswalkerType::Lolth),
        "lukka" => Some(PlaneswalkerType::Lukka),
        "minsc" => Some(PlaneswalkerType::Minsc),
        "mordenkainen" => Some(PlaneswalkerType::Mordenkainen),
        "nahiri" => Some(PlaneswalkerType::Nahiri),
        "narset" => Some(PlaneswalkerType::Narset),
        "niko" => Some(PlaneswalkerType::Niko),
        "nissa" => Some(PlaneswalkerType::Nissa),
        "nixilis" => Some(PlaneswalkerType::Nixilis),
        "oko" => Some(PlaneswalkerType::Oko),
        "quintorius" => Some(PlaneswalkerType::Quintorius),
        "ral" => Some(PlaneswalkerType::Ral),
        "rowan" => Some(PlaneswalkerType::Rowan),
        "saheeli" => Some(PlaneswalkerType::Saheeli),
        "samut" => Some(PlaneswalkerType::Samut),
        "sarkhan" => Some(PlaneswalkerType::Sarkhan),
        "serra" => Some(PlaneswalkerType::Serra),
        "sivitri" => Some(PlaneswalkerType::Sivitri),
        "sorin" => Some(PlaneswalkerType::Sorin),
        "szat" => Some(PlaneswalkerType::Szat),
        "tamiyo" => Some(PlaneswalkerType::Tamiyo),
        "tasha" => Some(PlaneswalkerType::Tasha),
        "teferi" => Some(PlaneswalkerType::Teferi),
        "teyo" => Some(PlaneswalkerType::Teyo),
        "tezzeret" => Some(PlaneswalkerType::Tezzeret),
        "tibalt" => Some(PlaneswalkerType::Tibalt),
        "tyvar" => Some(PlaneswalkerType::Tyvar),
        "ugin" => Some(PlaneswalkerType::Ugin),
        "urza" => Some(PlaneswalkerType::Urza),
        "venser" => Some(PlaneswalkerType::Venser),
        "vivien" => Some(PlaneswalkerType::Vivien),
        "vraska" => Some(PlaneswalkerType::Vraska),
        "vronos" => Some(PlaneswalkerType::Vronos),
        "will" => Some(PlaneswalkerType::Will),
        "windgrace" => Some(PlaneswalkerType::Windgrace),
        "wrenn" => Some(PlaneswalkerType::Wrenn),
        "xenagos" => Some(PlaneswalkerType::Xenagos),
        "yanggu" => Some(PlaneswalkerType::Yanggu),
        "yanling" => Some(PlaneswalkerType::Yanling),
        "zariel" => Some(PlaneswalkerType::Zariel),
        _ => None,
    }
}

pub fn parse_spelltype(s: &str) -> Option<SpellType> {
    match s.to_lowercase().as_str() {
        "adventure" => Some(SpellType::Adventure),
        "arcane" => Some(SpellType::Arcane),
        "lesson" => Some(SpellType::Lesson),
        "omen" => Some(SpellType::Omen),
        "trap" => Some(SpellType::Trap),
        _ => None,
    }
}

pub fn parse_creaturetype(s: &str) -> Option<CreatureType> {
    match s.to_lowercase().as_str() {
        "advisor" => Some(CreatureType::Advisor),
        "aetherborn" => Some(CreatureType::Aetherborn),
        "alien" => Some(CreatureType::Alien),
        "ally" => Some(CreatureType::Ally),
        "angel" => Some(CreatureType::Angel),
        "antelope" => Some(CreatureType::Antelope),
        "ape" => Some(CreatureType::Ape),
        "archer" => Some(CreatureType::Archer),
        "archon" => Some(CreatureType::Archon),
        "armadillo" => Some(CreatureType::Armadillo),
        "army" => Some(CreatureType::Army),
        "artificer" => Some(CreatureType::Artificer),
        "assassin" => Some(CreatureType::Assassin),
        "assembly-worker" => Some(CreatureType::AssemblyWorker),
        "astartes" => Some(CreatureType::Astartes),
        "atog" => Some(CreatureType::Atog),
        "aurochs" => Some(CreatureType::Aurochs),
        "avatar" => Some(CreatureType::Avatar),
        "azra" => Some(CreatureType::Azra),
        "badger" => Some(CreatureType::Badger),
        "balloon" => Some(CreatureType::Balloon),
        "barbarian" => Some(CreatureType::Barbarian),
        "bard" => Some(CreatureType::Bard),
        "basilisk" => Some(CreatureType::Basilisk),
        "bat" => Some(CreatureType::Bat),
        "bear" => Some(CreatureType::Bear),
        "beast" => Some(CreatureType::Beast),
        "beaver" => Some(CreatureType::Beaver),
        "beeble" => Some(CreatureType::Beeble),
        "beholder" => Some(CreatureType::Beholder),
        "berserker" => Some(CreatureType::Berserker),
        "bird" => Some(CreatureType::Bird),
        "bison" => Some(CreatureType::Bison),
        "blinkmoth" => Some(CreatureType::Blinkmoth),
        "boar" => Some(CreatureType::Boar),
        "bringer" => Some(CreatureType::Bringer),
        "brushwagg" => Some(CreatureType::Brushwagg),
        "camarid" => Some(CreatureType::Camarid),
        "camel" => Some(CreatureType::Camel),
        "capybara" => Some(CreatureType::Capybara),
        "caribou" => Some(CreatureType::Caribou),
        "carrier" => Some(CreatureType::Carrier),
        "cat" => Some(CreatureType::Cat),
        "centaur" => Some(CreatureType::Centaur),
        "child" => Some(CreatureType::Child),
        "chimera" => Some(CreatureType::Chimera),
        "citizen" => Some(CreatureType::Citizen),
        "cleric" => Some(CreatureType::Cleric),
        "clown" => Some(CreatureType::Clown),
        "cockatrice" => Some(CreatureType::Cockatrice),
        "construct" => Some(CreatureType::Construct),
        "coward" => Some(CreatureType::Coward),
        "coyote" => Some(CreatureType::Coyote),
        "crab" => Some(CreatureType::Crab),
        "crocodile" => Some(CreatureType::Crocodile),
        "c'tan" => Some(CreatureType::Ctan),
        "custodes" => Some(CreatureType::Custodes),
        "cyberman" => Some(CreatureType::Cyberman),
        "cyclops" => Some(CreatureType::Cyclops),
        "dalek" => Some(CreatureType::Dalek),
        "dauthi" => Some(CreatureType::Dauthi),
        "demigod" => Some(CreatureType::Demigod),
        "demon" => Some(CreatureType::Demon),
        "deserter" => Some(CreatureType::Deserter),
        "detective" => Some(CreatureType::Detective),
        "devil" => Some(CreatureType::Devil),
        "dinosaur" => Some(CreatureType::Dinosaur),
        "djinn" => Some(CreatureType::Djinn),
        "doctor" => Some(CreatureType::Doctor),
        "dog" => Some(CreatureType::Dog),
        "dragon" => Some(CreatureType::Dragon),
        "drake" => Some(CreatureType::Drake),
        "dreadnought" => Some(CreatureType::Dreadnought),
        "drix" => Some(CreatureType::Drix),
        "drone" => Some(CreatureType::Drone),
        "druid" => Some(CreatureType::Druid),
        "dryad" => Some(CreatureType::Dryad),
        "dwarf" => Some(CreatureType::Dwarf),
        "echidna" => Some(CreatureType::Echidna),
        "efreet" => Some(CreatureType::Efreet),
        "egg" => Some(CreatureType::Egg),
        "elder" => Some(CreatureType::Elder),
        "eldrazi" => Some(CreatureType::Eldrazi),
        "elemental" => Some(CreatureType::Elemental),
        "elephant" => Some(CreatureType::Elephant),
        "elf" => Some(CreatureType::Elf),
        "elk" => Some(CreatureType::Elk),
        "employee" => Some(CreatureType::Employee),
        "eye" => Some(CreatureType::Eye),
        "faerie" => Some(CreatureType::Faerie),
        "ferret" => Some(CreatureType::Ferret),
        "fish" => Some(CreatureType::Fish),
        "flagbearer" => Some(CreatureType::Flagbearer),
        "fox" => Some(CreatureType::Fox),
        "fractal" => Some(CreatureType::Fractal),
        "frog" => Some(CreatureType::Frog),
        "fungus" => Some(CreatureType::Fungus),
        "gamer" => Some(CreatureType::Gamer),
        "gargoyle" => Some(CreatureType::Gargoyle),
        "germ" => Some(CreatureType::Germ),
        "giant" => Some(CreatureType::Giant),
        "giraffe" => Some(CreatureType::Giraffe),
        "gith" => Some(CreatureType::Gith),
        "glimmer" => Some(CreatureType::Glimmer),
        "gnoll" => Some(CreatureType::Gnoll),
        "gnome" => Some(CreatureType::Gnome),
        "goat" => Some(CreatureType::Goat),
        "goblin" => Some(CreatureType::Goblin),
        "god" => Some(CreatureType::God),
        "golem" => Some(CreatureType::Golem),
        "gorgon" => Some(CreatureType::Gorgon),
        "graveborn" => Some(CreatureType::Graveborn),
        "gremlin" => Some(CreatureType::Gremlin),
        "griffin" => Some(CreatureType::Griffin),
        "guest" => Some(CreatureType::Guest),
        "hag" => Some(CreatureType::Hag),
        "halfling" => Some(CreatureType::Halfling),
        "hamster" => Some(CreatureType::Hamster),
        "harpy" => Some(CreatureType::Harpy),
        "hedgehog" => Some(CreatureType::Hedgehog),
        "hellion" => Some(CreatureType::Hellion),
        "hero" => Some(CreatureType::Hero),
        "hippo" => Some(CreatureType::Hippo),
        "hippogriff" => Some(CreatureType::Hippogriff),
        "homarid" => Some(CreatureType::Homarid),
        "homunculus" => Some(CreatureType::Homunculus),
        "horror" => Some(CreatureType::Horror),
        "horse" => Some(CreatureType::Horse),
        "human" => Some(CreatureType::Human),
        "hydra" => Some(CreatureType::Hydra),
        "hyena" => Some(CreatureType::Hyena),
        "illusion" => Some(CreatureType::Illusion),
        "imp" => Some(CreatureType::Imp),
        "incarnation" => Some(CreatureType::Incarnation),
        "inkling" => Some(CreatureType::Inkling),
        "inquisitor" => Some(CreatureType::Inquisitor),
        "insect" => Some(CreatureType::Insect),
        "jackal" => Some(CreatureType::Jackal),
        "jellyfish" => Some(CreatureType::Jellyfish),
        "juggernaut" => Some(CreatureType::Juggernaut),
        "kangaroo" => Some(CreatureType::Kangaroo),
        "kavu" => Some(CreatureType::Kavu),
        "kirin" => Some(CreatureType::Kirin),
        "kithkin" => Some(CreatureType::Kithkin),
        "knight" => Some(CreatureType::Knight),
        "kobold" => Some(CreatureType::Kobold),
        "kor" => Some(CreatureType::Kor),
        "kraken" => Some(CreatureType::Kraken),
        "llama" => Some(CreatureType::Llama),
        "lamia" => Some(CreatureType::Lamia),
        "lammasu" => Some(CreatureType::Lammasu),
        "leech" => Some(CreatureType::Leech),
        "lemur" => Some(CreatureType::Lemur),
        "leviathan" => Some(CreatureType::Leviathan),
        "lhurgoyf" => Some(CreatureType::Lhurgoyf),
        "licid" => Some(CreatureType::Licid),
        "lizard" => Some(CreatureType::Lizard),
        "lobster" => Some(CreatureType::Lobster),
        "manticore" => Some(CreatureType::Manticore),
        "masticore" => Some(CreatureType::Masticore),
        "mercenary" => Some(CreatureType::Mercenary),
        "merfolk" => Some(CreatureType::Merfolk),
        "metathran" => Some(CreatureType::Metathran),
        "minion" => Some(CreatureType::Minion),
        "minotaur" => Some(CreatureType::Minotaur),
        "mite" => Some(CreatureType::Mite),
        "mole" => Some(CreatureType::Mole),
        "monger" => Some(CreatureType::Monger),
        "mongoose" => Some(CreatureType::Mongoose),
        "monk" => Some(CreatureType::Monk),
        "monkey" => Some(CreatureType::Monkey),
        "moogle" => Some(CreatureType::Moogle),
        "moonfolk" => Some(CreatureType::Moonfolk),
        "mount" => Some(CreatureType::Mount),
        "mouse" => Some(CreatureType::Mouse),
        "mutant" => Some(CreatureType::Mutant),
        "myr" => Some(CreatureType::Myr),
        "mystic" => Some(CreatureType::Mystic),
        "nautilus" => Some(CreatureType::Nautilus),
        "necron" => Some(CreatureType::Necron),
        "nephilim" => Some(CreatureType::Nephilim),
        "nightmare" => Some(CreatureType::Nightmare),
        "nightstalker" => Some(CreatureType::Nightstalker),
        "ninja" => Some(CreatureType::Ninja),
        "noble" => Some(CreatureType::Noble),
        "noggle" => Some(CreatureType::Noggle),
        "nomad" => Some(CreatureType::Nomad),
        "nymph" => Some(CreatureType::Nymph),
        "octopus" => Some(CreatureType::Octopus),
        "ogre" => Some(CreatureType::Ogre),
        "ooze" => Some(CreatureType::Ooze),
        "orb" => Some(CreatureType::Orb),
        "orc" => Some(CreatureType::Orc),
        "orgg" => Some(CreatureType::Orgg),
        "otter" => Some(CreatureType::Otter),
        "ouphe" => Some(CreatureType::Ouphe),
        "ox" => Some(CreatureType::Ox),
        "oyster" => Some(CreatureType::Oyster),
        "pangolin" => Some(CreatureType::Pangolin),
        "peasant" => Some(CreatureType::Peasant),
        "pegasus" => Some(CreatureType::Pegasus),
        "pentavite" => Some(CreatureType::Pentavite),
        "performer" => Some(CreatureType::Performer),
        "pest" => Some(CreatureType::Pest),
        "phelddagrif" => Some(CreatureType::Phelddagrif),
        "phoenix" => Some(CreatureType::Phoenix),
        "phyrexian" => Some(CreatureType::Phyrexian),
        "pilot" => Some(CreatureType::Pilot),
        "pincher" => Some(CreatureType::Pincher),
        "pirate" => Some(CreatureType::Pirate),
        "plant" => Some(CreatureType::Plant),
        "platypus" => Some(CreatureType::Platypus),
        "porcupine" => Some(CreatureType::Porcupine),
        "possum" => Some(CreatureType::Possum),
        "praetor" => Some(CreatureType::Praetor),
        "primarch" => Some(CreatureType::Primarch),
        "prism" => Some(CreatureType::Prism),
        "processor" => Some(CreatureType::Processor),
        "qu" => Some(CreatureType::Qu),
        "rabbit" => Some(CreatureType::Rabbit),
        "raccoon" => Some(CreatureType::Raccoon),
        "ranger" => Some(CreatureType::Ranger),
        "rat" => Some(CreatureType::Rat),
        "rebel" => Some(CreatureType::Rebel),
        "reflection" => Some(CreatureType::Reflection),
        "rhino" => Some(CreatureType::Rhino),
        "rigger" => Some(CreatureType::Rigger),
        "robot" => Some(CreatureType::Robot),
        "rogue" => Some(CreatureType::Rogue),
        "sable" => Some(CreatureType::Sable),
        "salamander" => Some(CreatureType::Salamander),
        "samurai" => Some(CreatureType::Samurai),
        "sand" => Some(CreatureType::Sand),
        "saproling" => Some(CreatureType::Saproling),
        "satyr" => Some(CreatureType::Satyr),
        "scarecrow" => Some(CreatureType::Scarecrow),
        "scientist" => Some(CreatureType::Scientist),
        "scion" => Some(CreatureType::Scion),
        "scorpion" => Some(CreatureType::Scorpion),
        "scout" => Some(CreatureType::Scout),
        "sculpture" => Some(CreatureType::Sculpture),
        "seal" => Some(CreatureType::Seal),
        "serf" => Some(CreatureType::Serf),
        "serpent" => Some(CreatureType::Serpent),
        "servo" => Some(CreatureType::Servo),
        "shade" => Some(CreatureType::Shade),
        "shaman" => Some(CreatureType::Shaman),
        "shapeshifter" => Some(CreatureType::Shapeshifter),
        "shark" => Some(CreatureType::Shark),
        "sheep" => Some(CreatureType::Sheep),
        "siren" => Some(CreatureType::Siren),
        "skeleton" => Some(CreatureType::Skeleton),
        "skunk" => Some(CreatureType::Skunk),
        "slith" => Some(CreatureType::Slith),
        "sliver" => Some(CreatureType::Sliver),
        "sloth" => Some(CreatureType::Sloth),
        "slug" => Some(CreatureType::Slug),
        "snail" => Some(CreatureType::Snail),
        "snake" => Some(CreatureType::Snake),
        "soldier" => Some(CreatureType::Soldier),
        "soltari" => Some(CreatureType::Soltari),
        "sorcerer" => Some(CreatureType::Sorcerer),
        "spawn" => Some(CreatureType::Spawn),
        "specter" => Some(CreatureType::Specter),
        "spellshaper" => Some(CreatureType::Spellshaper),
        "sphinx" => Some(CreatureType::Sphinx),
        "spider" => Some(CreatureType::Spider),
        "spike" => Some(CreatureType::Spike),
        "spirit" => Some(CreatureType::Spirit),
        "splinter" => Some(CreatureType::Splinter),
        "sponge" => Some(CreatureType::Sponge),
        "squid" => Some(CreatureType::Squid),
        "squirrel" => Some(CreatureType::Squirrel),
        "starfish" => Some(CreatureType::Starfish),
        "surrakar" => Some(CreatureType::Surrakar),
        "survivor" => Some(CreatureType::Survivor),
        "symbiote" => Some(CreatureType::Symbiote),
        "synth" => Some(CreatureType::Synth),
        "tentacle" => Some(CreatureType::Tentacle),
        "tetravite" => Some(CreatureType::Tetravite),
        "thalakos" => Some(CreatureType::Thalakos),
        "thopter" => Some(CreatureType::Thopter),
        "thrull" => Some(CreatureType::Thrull),
        "tiefling" => Some(CreatureType::Tiefling),
        "time lord" => Some(CreatureType::TimeLord),
        "toy" => Some(CreatureType::Toy),
        "treefolk" => Some(CreatureType::Treefolk),
        "trilobite" => Some(CreatureType::Trilobite),
        "triskelavite" => Some(CreatureType::Triskelavite),
        "troll" => Some(CreatureType::Troll),
        "turtle" => Some(CreatureType::Turtle),
        "tyranid" => Some(CreatureType::Tyranid),
        "unicorn" => Some(CreatureType::Unicorn),
        "utrom" => Some(CreatureType::Utrom),
        "vampire" => Some(CreatureType::Vampire),
        "varmint" => Some(CreatureType::Varmint),
        "vedalken" => Some(CreatureType::Vedalken),
        "villain" => Some(CreatureType::Villain),
        "volver" => Some(CreatureType::Volver),
        "wall" => Some(CreatureType::Wall),
        "walrus" => Some(CreatureType::Walrus),
        "warlock" => Some(CreatureType::Warlock),
        "warrior" => Some(CreatureType::Warrior),
        "weasel" => Some(CreatureType::Weasel),
        "weird" => Some(CreatureType::Weird),
        "werewolf" => Some(CreatureType::Werewolf),
        "whale" => Some(CreatureType::Whale),
        "wizard" => Some(CreatureType::Wizard),
        "wolf" => Some(CreatureType::Wolf),
        "wolverine" => Some(CreatureType::Wolverine),
        "wombat" => Some(CreatureType::Wombat),
        "worm" => Some(CreatureType::Worm),
        "wraith" => Some(CreatureType::Wraith),
        "wurm" => Some(CreatureType::Wurm),
        "yeti" => Some(CreatureType::Yeti),
        "zombie" => Some(CreatureType::Zombie),
        "zubera" => Some(CreatureType::Zubera),
        _ => None,
    }
}

pub fn parse_planartype(s: &str) -> Option<PlanarType> {
    match s.to_lowercase().as_str() {
        "theabyss" => Some(PlanarType::TheAbyss),
        "alara" => Some(PlanarType::Alara),
        "alfavametraxis" => Some(PlanarType::AlfavaMetraxis),
        "amonkhet" => Some(PlanarType::Amonkhet),
        "androzaniminor" => Some(PlanarType::AndrozaniMinor),
        "antausia" => Some(PlanarType::Antausia),
        "apalapucia" => Some(PlanarType::Apalapucia),
        "arcavios" => Some(PlanarType::Arcavios),
        "arkhos" => Some(PlanarType::Arkhos),
        "avishkar" => Some(PlanarType::Avishkar),
        "azgol" => Some(PlanarType::Azgol),
        "belenon" => Some(PlanarType::Belenon),
        "bolasmeditationrealm" => Some(PlanarType::BolasMeditationRealm),
        "capenna" => Some(PlanarType::Capenna),
        "cridhe" => Some(PlanarType::Cridhe),
        "thedalekasylum" => Some(PlanarType::TheDalekAsylum),
        "darillium" => Some(PlanarType::Darillium),
        "dominaria" => Some(PlanarType::Dominaria),
        "earth" => Some(PlanarType::Earth),
        "echoir" => Some(PlanarType::Echoir),
        "eldraine" => Some(PlanarType::Eldraine),
        "equilor" => Some(PlanarType::Equilor),
        "ergamon" => Some(PlanarType::Ergamon),
        "fabacin" => Some(PlanarType::Fabacin),
        "fiora" => Some(PlanarType::Fiora),
        "gallifrey" => Some(PlanarType::Gallifrey),
        "gargantikar" => Some(PlanarType::Gargantikar),
        "gobakhan" => Some(PlanarType::Gobakhan),
        "horseheadnebula" => Some(PlanarType::HorseheadNebula),
        "ikoria" => Some(PlanarType::Ikoria),
        "innistrad" => Some(PlanarType::Innistrad),
        "iquatana" => Some(PlanarType::Iquatana),
        "ir" => Some(PlanarType::Ir),
        "ixalan" => Some(PlanarType::Ixalan),
        "kaldheim" => Some(PlanarType::Kaldheim),
        "kamigawa" => Some(PlanarType::Kamigawa),
        "kandoka" => Some(PlanarType::Kandoka),
        "karsus" => Some(PlanarType::Karsus),
        "kephalai" => Some(PlanarType::Kephalai),
        "kinshala" => Some(PlanarType::Kinshala),
        "kolbahan" => Some(PlanarType::Kolbahan),
        "kylem" => Some(PlanarType::Kylem),
        "kyneth" => Some(PlanarType::Kyneth),
        "thelibrary" => Some(PlanarType::TheLibrary),
        "lorwyn" => Some(PlanarType::Lorwyn),
        "luvion" => Some(PlanarType::Luvion),
        "mars" => Some(PlanarType::Mars),
        "mercadia" => Some(PlanarType::Mercadia),
        "mirrodin" => Some(PlanarType::Mirrodin),
        "moag" => Some(PlanarType::Moag),
        "mongseng" => Some(PlanarType::Mongseng),
        "moon" => Some(PlanarType::Moon),
        "muraganda" => Some(PlanarType::Muraganda),
        "necros" => Some(PlanarType::Necros),
        "newearth" => Some(PlanarType::NewEarth),
        "newphyrexia" => Some(PlanarType::NewPhyrexia),
        "outsidemuttersspiral" => Some(PlanarType::OutsideMuttersSpiral),
        "phyrexia" => Some(PlanarType::Phyrexia),
        "pyrulea" => Some(PlanarType::Pyrulea),
        "rabiah" => Some(PlanarType::Rabiah),
        "rath" => Some(PlanarType::Rath),
        "ravnica" => Some(PlanarType::Ravnica),
        "regatha" => Some(PlanarType::Regatha),
        "segovia" => Some(PlanarType::Segovia),
        "serrasrealm" => Some(PlanarType::SerrasRealm),
        "shadowmoor" => Some(PlanarType::Shadowmoor),
        "shandalar" => Some(PlanarType::Shandalar),
        "shenmeng" => Some(PlanarType::Shenmeng),
        "skaro" => Some(PlanarType::Skaro),
        "spacecraft" => Some(PlanarType::Spacecraft),
        "tarkir" => Some(PlanarType::Tarkir),
        "theros" => Some(PlanarType::Theros),
        "time" => Some(PlanarType::Time),
        "trenzalore" => Some(PlanarType::Trenzalore),
        "ulgrotha" => Some(PlanarType::Ulgrotha),
        "unknownplanet" => Some(PlanarType::UnknownPlanet),
        "valla" => Some(PlanarType::Valla),
        "vryn" => Some(PlanarType::Vryn),
        "wildfire" => Some(PlanarType::Wildfire),
        "xerex" => Some(PlanarType::Xerex),
        "zendikar" => Some(PlanarType::Zendikar),
        "zhalfir" => Some(PlanarType::Zhalfir),
        _ => None,
    }
}

pub fn parse_dungeontype(s: &str) -> Option<DungeonType> {
    match s.to_lowercase().as_str() {
        "undercity" => Some(DungeonType::Undercity),
        _ => None,
    }
}

pub fn parse_battletype(s: &str) -> Option<BattleType> {
    match s.to_lowercase().as_str() {
        "siege" => Some(BattleType::Siege),
        _ => None,
    }
}

pub fn parse_subtype(s: &str, card_types: &[CardType]) -> Option<Subtype> {
    // If we have "time" and "lord" combined, handled at caller.
    // Try matching in order of the active card types first to avoid collision.
    let s_lower = s.to_lowercase();
    
    // 1. Creature & Kindred
    if card_types.contains(&CardType::Creature) || card_types.contains(&CardType::Kindred) {
        if let Some(ct) = parse_creaturetype(&s_lower) {
            return Some(Subtype::Creature(ct));
        }
    }
    
    // 2. Artifact
    if card_types.contains(&CardType::Artifact) {
        if let Some(at) = parse_artifacttype(&s_lower) {
            return Some(Subtype::Artifact(at));
        }
    }
    
    // 3. Enchantment
    if card_types.contains(&CardType::Enchantment) {
        if let Some(et) = parse_enchantmenttype(&s_lower) {
            return Some(Subtype::Enchantment(et));
        }
    }
    
    // 4. Land
    if card_types.contains(&CardType::Land) {
        if let Some(lt) = parse_landtype(&s_lower) {
            return Some(Subtype::Land(lt));
        }
    }
    
    // 5. Planeswalker
    if card_types.contains(&CardType::Planeswalker) {
        if let Some(pt) = parse_planeswalkertype(&s_lower) {
            return Some(Subtype::Planeswalker(pt));
        }
    }
    
    // 6. Spell
    if card_types.contains(&CardType::Instant) || card_types.contains(&CardType::Sorcery) {
        if let Some(st) = parse_spelltype(&s_lower) {
            return Some(Subtype::Spell(st));
        }
    }
    
    // 7. Battle
    if card_types.contains(&CardType::Battle) {
        if let Some(bt) = parse_battletype(&s_lower) {
            return Some(Subtype::Battle(bt));
        }
    }
    
    // 8. Planar
    if card_types.contains(&CardType::Plane) {
        if let Some(pt) = parse_planartype(&s_lower) {
            return Some(Subtype::Planar(pt));
        }
    }
    
    // 9. Dungeon
    if card_types.contains(&CardType::Dungeon) {
        if let Some(dt) = parse_dungeontype(&s_lower) {
            return Some(Subtype::Dungeon(dt));
        }
    }

    // General fallback lookup across all subtypes
    if let Some(ct) = parse_creaturetype(&s_lower) {
        return Some(Subtype::Creature(ct));
    }
    if let Some(at) = parse_artifacttype(&s_lower) {
        return Some(Subtype::Artifact(at));
    }
    if let Some(et) = parse_enchantmenttype(&s_lower) {
        return Some(Subtype::Enchantment(et));
    }
    if let Some(lt) = parse_landtype(&s_lower) {
        return Some(Subtype::Land(lt));
    }
    if let Some(pt) = parse_planeswalkertype(&s_lower) {
        return Some(Subtype::Planeswalker(pt));
    }
    if let Some(st) = parse_spelltype(&s_lower) {
        return Some(Subtype::Spell(st));
    }
    if let Some(bt) = parse_battletype(&s_lower) {
        return Some(Subtype::Battle(bt));
    }
    if let Some(pt) = parse_planartype(&s_lower) {
        return Some(Subtype::Planar(pt));
    }
    if let Some(dt) = parse_dungeontype(&s_lower) {
        return Some(Subtype::Dungeon(dt));
    }

    None
}
